import {Metadata} from 'next';

export const metadata: Metadata = {
    title: 'About page',
    description: 'About page generated by create next app',
};

export default function About () {
    return (
        <h3>Select sub item</h3>
    );
}
